version: 2

orbs:
  node: circleci/node@3.0.1

jobs:
  build:
    docker:
      - image: 'node:12.18.2'
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - persist_to_workspace:
        root: .
        paths: dist
  publish:
    docker:
      - image: 'node:12.18.2'
    steps:
      - checkout
      - attach_workspace:
        at: app
      - run:
        name: Install and configure dependencies
        command: |
          npm install -g --silent gh-pages
          git config user.email "circleci@circleci"
          git config user.name "ci-build"
      - run:
        name: Deploy app to gh-pages branch
        command: gh-pages --dist app/dist
workflows:
  version: 2
  deploy:
    jobs:
      - build
      - publish:
        requires:
          - build