# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  node: circleci/node@3.0.1

jobs:
  setup-node:
    docker:
      - image: 'node:12.18.2'
    steps:
      - checkout
      - run: node --version
workflows:
  deploy:
    jobs:
      - setup-node