# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  node: circleci/node@3.0.1

jobs:
  build-and-publish:
    docker:
      - image: 'node:12.18.2'
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run: cd dist
      - checkout
      - run: ./deploy.sh
workflows:
  version: 2.1
  main:
    jobs:
      - build-and-publish